export interface Project {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  image: string;
  techStack: string[];
  liveUrl?: string;
  githubUrl?: string;
  featured: boolean;
  screenshots?: string[];
}

export const projects: Project[] = [
  {
    id: "project-1",
    title: "SiPena",
    description: "Sistem Perizinan Akademik yang dirancang untuk memenuhi kebutuhan berbagai macam perizinan surat menyurat menggunakan platform digital",
    longDescription: "Sistem Perizinan Akademik yang dirancang untuk memenuhi kebutuhan berbagai macam perizinan surat menyurat menggunakan platform digital",
    image: "/projects/sipena/sipena.webp",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Go", "Gin", "MariaDB", "Redis"],
    liveUrl: "https://www.sipena-smkn2.dedyn.io/",
    githubUrl: "https://github.com/e-letter/e-letter-web",
    featured: true,
    screenshots: [
      "/projects/sipena/login-siswa.webp",
      "/projects/sipena/home-siswa.webp",
      "/projects/sipena/daftar-siswa.webp",
      "/projects/sipena/masuk-siswa.webp",
      "/projects/sipena/keluar-siswa.webp",
      "/projects/sipena/notif-siswa.webp",
      "/projects/sipena/otp-siswa.webp",
      "/projects/sipena/panduan1-siswa.webp",
      "/projects/sipena/panduan2-siswa.webp",
      "/projects/sipena/profil-siswa.webp",
      "/projects/sipena/riwayat-siswa.webp",
      "/projects/sipena/log-siswa.webp",
    ],
  },
  {
    id: "project-2",
    title: "RuangTeduh",
    description: "Aplikasi pencarian coffee shop bergaya neo-brutalism untuk menemukan tempat yang tenang, estetik, dan produktif berdasarkan mood, atmosfer, dan vibes.",
    longDescription: "RuangTeduh adalah aplikasi pencarian coffee shop bergaya neo-brutalism yang mengutamakan pengalaman emosional, bukan hanya rating dan menu. Pengguna dapat mencari café berdasarkan nama, memfilter berdasarkan mood dan vibes, melihat rekomendasi serta detail dinamis setiap tempat, dan menyimpan coffee shop favorit untuk menemukan ruang yang cocok untuk fokus, healing, night coding, atau bekerja sendiri.",
    image: "/projects/ruang-teduh/1dashboard.webp",
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "shadcn/ui", "Supabase"],
    githubUrl: "https://github.com/Mufid2225/ruangteduh",
    liveUrl: undefined,
    featured: true,
    screenshots: [
      "/projects/ruang-teduh/2recommend.webp",
      "/projects/ruang-teduh/3searchfilter-1.webp",
      "/projects/ruang-teduh/4searchfilter-2.webp",
      "/projects/ruang-teduh/5detail.webp",
      "/projects/ruang-teduh/6favorite.webp",
    ],
  },
  {
    id: "project-3",
    title: "9Router",
    description: "FREE AI Router & Token Saver — single OpenAI-compatible endpoint untuk routing ke 40+ AI provider dengan smart fallback dan kompresi token, dihosting via Hugging Face",
    longDescription: "FREE AI Router & Token Saver — single OpenAI-compatible endpoint untuk routing ke 40+ AI provider dengan smart fallback dan kompresi token, dihosting via Hugging Face",
    image: "/projects/9router/1login-router.webp",
    techStack: ["Next.js", "React", "Tailwind CSS", "SQLite", "Express"],
    screenshots: [
      "/projects/9router/2home-router.webp",
      "/projects/9router/3provider-router.webp",
      "/projects/9router/4model-router.webp",
      "/projects/9router/5usage-router.webp",
    ],
    liveUrl: "https://neriss4-9router-database-demo.hf.space/",
    githubUrl: "https://huggingface.co/spaces/Neriss4/9router-database-demo/tree/main",
    featured: false,
  },
  {
    id: "project-4",
    title: "Kasir-App",
    description: "Aplikasi Point of Sale desktop untuk toko dan UMKM Indonesia dengan checkout, inventori, shift, laporan, serta pembayaran Tunai, Debit, dan QRIS.",
    longDescription: "Aplikasi Point of Sale desktop untuk toko dan UMKM Indonesia. Kasir-App menyediakan login SQLite dan RBAC, checkout atomik, pembayaran Tunai, Debit, dan Xendit QRIS sandbox, pengelolaan shift, inventori, riwayat transaksi, laporan, ekspor CSV/PDF, void/refund lokal, pengaturan toko, serta struk dinamis dengan barcode Code 128.",
    image: "/projects/kasir-app/1login-page.webp",
    techStack: ["Electron", "Next.js", "React", "TypeScript", "Tailwind CSS", "SQLite"],
    screenshots: [
      "/projects/kasir-app/2dashboard-page.webp",
      "/projects/kasir-app/3riwayat-page.webp",
      "/projects/kasir-app/4inventori-page.webp",
      "/projects/kasir-app/5laporan-page.webp",
      "/projects/kasir-app/6pengguna-page.webp",
      "/projects/kasir-app/7penggaturan-page.webp",
      "/projects/kasir-app/8profil-page.webp",
      "/projects/kasir-app/9trx-modal.webp",
      "/projects/kasir-app/10struk-modal.webp",
      "/projects/kasir-app/11ekspor-modal.webp",
      "/projects/kasir-app/12tambahproduk-modal.webp",
      "/projects/kasir-app/13shift-modal.webp",
    ],
    githubUrl: "https://github.com/Mufid2225/kasir-app",
    featured: true,
  },
  {
    id: "project-5",
    title: "Aligatour",
    description: "Website katalog tour and travel untuk menjelajahi paket wisata Malang, Batu, dan destinasi Jawa Timur serta melakukan reservasi melalui WhatsApp.",
    longDescription: "Aligatour adalah website katalog tour and travel yang menampilkan layanan wisata Malang, Batu, dan berbagai destinasi Jawa Timur. Pengunjung dapat melihat pilihan paket, harga, destinasi, fasilitas, syarat perjalanan, dan halaman detail untuk enam layanan, lalu menghubungi Aligatour melalui WhatsApp untuk reservasi. Website responsif ini juga dilengkapi informasi kontak, media sosial, dan metadata pada setiap halaman trip.",
    image: "/projects/aligatour/1dashboard.webp",
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Phosphor Icons", "Netlify"],
    screenshots: [
      "/projects/aligatour/2pilihanpaket1.webp",
      "/projects/aligatour/3pilihanpaket2.webp",
      "/projects/aligatour/4slogan.webp",
      "/projects/aligatour/5review.webp",
      "/projects/aligatour/6footer.webp",
      "/projects/aligatour/7detailhero.webp",
      "/projects/aligatour/8detailfacilities1.webp",
      "/projects/aligatour/9detailfacilities2.webp",
      "/projects/aligatour/10detailpaket.webp",
      "/projects/aligatour/11syarat.webp",
    ],
    liveUrl: "https://aligatour.netlify.app/",
    githubUrl: "https://github.com/Mufid2225/aligatour",
    featured: false,
  },
  {
    id: "project-6",
    title: "Profil GitHub",
    description: "README profil GitHub dengan hero SVG responsif bertema terminal yang menyesuaikan desktop, mobile, light mode, dan dark mode.",
    longDescription: "Profil GitHub personal dengan highlight hero SVG yang digenerasi melalui Node.js dan Sharp. Generator mengubah portrait menjadi ASCII art, lalu menyusun terminal-style identity dengan animasi typewriter, moving caret, scan beam, status indicator, serta metadata SVG yang aksesibel. Empat varian SVG untuk desktop/mobile dan light/dark theme dipilih otomatis melalui elemen picture. README juga merangkum fokus pengembangan, featured projects, categorized tech stack, dan kontak dalam tampilan yang konsisten.",
    image: "/projects/profil-github/1hero.webp",
    techStack: ["SVG", "JavaScript", "Node.js", "Sharp", "GitHub Markdown"],
    screenshots: [
      "/projects/profil-github/2aboutfocus.webp",
      "/projects/profil-github/3featured.webp",
      "/projects/profil-github/5contribution.webp",
      "/projects/profil-github/4footer.webp",
    ],
    liveUrl: "https://github.com/Mufid2225",
    githubUrl: "https://github.com/Mufid2225/Mufid2225",
    featured: false,
  },
  {
    id: "project-7",
    title: "Nerrisa Bot",
    description: "Asisten AI Telegram privat untuk analisis pasar dan ekonomi, pencarian web, pengelolaan tugas sekolah, pemrosesan file, serta memory berbasis SQLite.",
    longDescription: "Nerrisa Bot adalah asisten AI Telegram privat yang menggunakan 9router sebagai AI engine. Bot menggabungkan data Yahoo Finance, Alpha Vantage, dan Financial Modeling Prep untuk analisis saham, market, serta ekonomi global; memakai Tavily, NewsAPI, dan SerpAPI untuk pencarian web berjenjang; mengelola tugas sekolah dan reminder; memproses gambar melalui OCR serta mengekstrak PDF dan DOCX; dan menyimpan percakapan, memory, serta knowledge graph dalam SQLite. Akses perintah dibatasi ke Telegram user ID yang dikonfigurasi.",
    image: "/projects/telegram-bot/1profil.webp",
    techStack: ["JavaScript", "Node.js", "Telegraf", "SQLite", "9router", "Tesseract.js"],
    screenshots: [
      "/projects/telegram-bot/2start.webp",
      "/projects/telegram-bot/3fitur.webp",
    ],
    liveUrl: "https://t.me/nerrisa_Bot",
    githubUrl: "https://github.com/Mufid2225/ai-telegram-bot",
    featured: false,
  },
  {
    id: "project-8",
    title: "ZeroCost.ai",
    description: "Direktori katalog penyedia AI, API, dan developer tools dengan free tier. Terdiri dari 15 penyedia AI yang sudah diverifikasi, teruji, dan dikatalogkan secara manual.",
    longDescription: "ZeroCost.ai adalah direktori katalog penyedia AI, API, dan developer tools dengan free tier. Dibangun sebagai katalog yang terverifikasi — hanya admin yang menguji dan menambahkan penyedia setelah verifikasi. Pengguna dapat menjelajahi, mencari, memfilter, dan mengakses kode untuk integrasi instan.",
    image: "/projects/zerocost/zerocost1.webp",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    githubUrl: "https://github.com/Mufid2225/zerocost",
    featured: false,
    screenshots: [
      "/projects/zerocost/zerocost2.webp",
      "/projects/zerocost/zerocost3.webp",
      "/projects/zerocost/zerocost4.webp",
      "/projects/zerocost/zerocost5.webp",
      "/projects/zerocost/zerocost6.webp",
      "/projects/zerocost/zerocost7.webp",
      "/projects/zerocost/zerocost8.webp",
      "/projects/zerocost/zerocost9.webp",
      "/projects/zerocost/zerocost10.webp",
    ],
  },
];

export const skills = [
  "Next.js",
  "React",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Tailwind CSS",
  "Git",
  "Electron",
  "MySQL",
  "SQLite",
  "PostgreSQL",
  "Docker",
];

export const socialLinks = {
  email: "mufidarhaburizky08@gmail.com",
  github: "https://github.com/Mufid2225",
  instagram: "https://www.instagram.com/fidnotpid_?igsh=MTNtdXlnZ3Q4MTZ6dQ==",
  instagramUsername: "@fidnotpid_",
  telegram: "https://t.me/liltrustcorner",
  telegramUsername: "1dleraa",
  tiktok: "https://tiktok.com/@fidnotpid_",
  spotify: "https://open.spotify.com/user/ukzr6gcxytbxxc6omkq7cw3yl?si=X9NzvxqFS8qjPj8pjpWe4A",
};
